Repository javascript-tutorial/ar.javascript.info, pull requests merged in 2020-07, with the labels that each got.

#97 Newbranch function prototype
  1-js/01-getting-started/4-devtools/article.md
  1-js/02-first-steps/03-strict-mode/article.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
  1-js/06-advanced-functions/10-bind/article.md
  1-js/06-advanced-functions/12-arrow-functions/article.md
  1-js/08-prototypes/02-function-prototype/article.md
  1-js/99-js-misc/02-eval/article.md
  1-js/99-js-misc/03-currying-partials/article.md
Labels: needs +1

#94 developer console
  1-js/01-getting-started/4-devtools/article.md
  1-js/02-first-steps/03-strict-mode/article.md
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
  1-js/06-advanced-functions/10-bind/article.md
  1-js/06-advanced-functions/12-arrow-functions/article.md
  1-js/08-prototypes/02-function-prototype/article.md
  1-js/99-js-misc/02-eval/article.md
  1-js/99-js-misc/03-currying-partials/article.md
Labels: changes requested, needs +1

#98 Translate function-object to Ar
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/solution.md
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/task.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/solution.md
  1-js/06-advanced-functions/06-function-object/5-sum-many-brackets/task.md
  1-js/06-advanced-functions/06-function-object/article.md
Labels: needs +1

#96 Proxy and Reflect
  1-js/08-prototypes/03-native-prototypes/article.md
  1-js/99-js-misc/01-proxy/01-error-nonexisting/task.md
  1-js/99-js-misc/01-proxy/02-array-negative/solution.md
  1-js/99-js-misc/01-proxy/02-array-negative/task.md
  1-js/99-js-misc/01-proxy/03-observable/solution.md
  1-js/99-js-misc/01-proxy/03-observable/task.md
  1-js/99-js-misc/01-proxy/article.md
Labels: needs +1

#101 Constructor
  1-js/04-object-basics/06-constructor-new/article.md
Labels: review needed

#100 Translating Rest Parameters and Spread Operator to Arabic
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
Labels: review needed

#102 Translate Old Var to Ar
  1-js/06-advanced-functions/04-var/article.md
Labels: review needed

#105 Translating global object to Arabic
  1-js/06-advanced-functions/05-global-object/article.md
Labels: review needed

#103 promise-basics
  1-js/11-async/02-promise-basics/article.md
  1-js/11-async/03-promise-chaining/article.md
Labels: review needed

#104 Array Methods
  1-js/05-data-types/05-array-methods/article.md
Labels: review needed

#107 structure
  1-js/02-first-steps/02-structure/article.md
Labels: review needed

#108 Translate Prototypal inheritance to AR
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/solution.md
  1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/task.md
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/solution.md
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/task.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/solution.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/task.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/solution.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/task.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: review needed

#109 custom-errors
  1-js/10-error-handling/2-custom-errors/article.md
Labels: review needed

#110 Automated testing with Mocha
  1-js/03-code-quality/05-testing-mocha/article.md
Labels: review needed

#111 Object.keys, values, entries
  1-js/05-data-types/09-keys-values-entries/article.md
Labels: review needed

#112 Object.keys, values, entries tasks
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/solution.md
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/task.md
  1-js/05-data-types/09-keys-values-entries/02-count-properties/task.md
Labels: review needed

#113 Translate instanceof to AR
  1-js/09-classes/06-instanceof/1-strange-instanceof/solution.md
  1-js/09-classes/06-instanceof/1-strange-instanceof/task.md
  1-js/09-classes/06-instanceof/article.md
  1-js/09-classes/index.md
Labels: review needed

#114 Translating Strings to Arabic
  1-js/05-data-types/03-string/1-ucfirst/solution.md
  1-js/05-data-types/03-string/1-ucfirst/task.md
  1-js/05-data-types/03-string/2-check-spam/solution.md
  1-js/05-data-types/03-string/2-check-spam/task.md
  1-js/05-data-types/03-string/3-truncate/solution.md
  1-js/05-data-types/03-string/3-truncate/task.md
  1-js/05-data-types/03-string/4-extract-currency/task.md
  1-js/05-data-types/03-string/article.md
Labels: review needed

#115 Array Methods Tasks
  1-js/05-data-types/05-array-methods/1-camelcase/task.md
  1-js/05-data-types/05-array-methods/10-average-age/task.md
  1-js/05-data-types/05-array-methods/11-array-unique/solution.md
  1-js/05-data-types/05-array-methods/11-array-unique/task.md
  1-js/05-data-types/05-array-methods/12-reduce-object/task.md
  1-js/05-data-types/05-array-methods/2-filter-range/task.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/task.md
  1-js/05-data-types/05-array-methods/4-sort-back/task.md
  1-js/05-data-types/05-array-methods/5-copy-sort-array/task.md
  1-js/05-data-types/05-array-methods/6-array-get-names/task.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/solution.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/task.md
  1-js/05-data-types/05-array-methods/7-map-objects/task.md
  1-js/05-data-types/05-array-methods/8-sort-objects/task.md
  1-js/05-data-types/05-array-methods/9-shuffle/task.md
  1-js/05-data-types/05-array-methods/article.md
Labels: review needed

#116 Objects
  1-js/04-object-basics/01-object/2-hello-object/task.md
  1-js/04-object-basics/01-object/3-is-empty/solution.md
  1-js/04-object-basics/01-object/3-is-empty/task.md
  1-js/04-object-basics/01-object/5-sum-object/task.md
  1-js/04-object-basics/01-object/8-multiply-numeric/task.md
Labels: review needed

#117 Translate numbers to AR
  1-js/05-data-types/02-number/1-sum-interface/solution.md
  1-js/05-data-types/02-number/1-sum-interface/task.md
  1-js/05-data-types/02-number/2-why-rounded-down/solution.md
  1-js/05-data-types/02-number/2-why-rounded-down/task.md
  1-js/05-data-types/02-number/3-repeat-until-number/task.md
  1-js/05-data-types/02-number/4-endless-loop-error/solution.md
  1-js/05-data-types/02-number/4-endless-loop-error/task.md
  1-js/05-data-types/02-number/8-random-min-max/solution.md
  1-js/05-data-types/02-number/8-random-min-max/task.md
  1-js/05-data-types/02-number/9-random-int-min-max/solution.md
  1-js/05-data-types/02-number/9-random-int-min-max/task.md
  1-js/05-data-types/02-number/article.md
Labels: review needed

#118 Reference Type
  1-js/99-js-misc/04-reference-type/2-check-syntax/solution.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/task.md
  1-js/99-js-misc/04-reference-type/3-why-this/solution.md
  1-js/99-js-misc/04-reference-type/3-why-this/task.md
  1-js/99-js-misc/04-reference-type/article.md
Labels: review needed

#119 object-methods "this"
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/task.md
  1-js/04-object-basics/04-object-methods/7-calculator/task.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/solution.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/task.md
  1-js/04-object-basics/04-object-methods/article.md
Labels: review needed

#120 Objects
  1-js/04-object-basics/01-object/article.md
Labels: review needed

#121 Translating Closure to Arabic
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/solution.md
  1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
  1-js/06-advanced-functions/03-closure/10-make-army/solution.md
  1-js/06-advanced-functions/03-closure/10-make-army/task.md
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/solution.md
  1-js/06-advanced-functions/03-closure/2-closure-variable-access/task.md
  1-js/06-advanced-functions/03-closure/3-counter-independent/solution.md
  1-js/06-advanced-functions/03-closure/3-counter-independent/task.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/solution.md
  1-js/06-advanced-functions/03-closure/4-counter-object-independent/task.md
  1-js/06-advanced-functions/03-closure/5-function-in-if/solution.md
  1-js/06-advanced-functions/03-closure/5-function-in-if/task.md
  1-js/06-advanced-functions/03-closure/6-closure-sum/solution.md
  1-js/06-advanced-functions/03-closure/6-closure-sum/task.md
  1-js/06-advanced-functions/03-closure/7-let-scope/solution.md
  1-js/06-advanced-functions/03-closure/7-let-scope/task.md
  1-js/06-advanced-functions/03-closure/8-filter-through-function/solution.md
  1-js/06-advanced-functions/03-closure/8-filter-through-function/task.md
  1-js/06-advanced-functions/03-closure/9-sort-by-field/task.md
  1-js/06-advanced-functions/03-closure/article.md
Labels: review needed

#122 second edit to objects article
  1-js/04-object-basics/01-object/article.md
Labels: review needed

#126 setTimeout & setInterval
  1-js/06-advanced-functions/08-settimeout-setinterval/article.md
  2-ui/1-document/01-browser-environment/article.md
Labels: needs +1

#127 Improve translation
  1-js/06-advanced-functions/06-function-object/2-counter-inc-dec/solution.md
Labels: needs +1

#87 translate DOM-tree topic into Arabic
  2-ui/1-document/02-dom-nodes/article.md
Labels: needs +1

#123 final edit to objects article
  1-js/04-object-basics/01-object/article.md
Labels: needs +1
